# Generated by Django 4.2.3 on 2023-07-05 03:25

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('fabrication', models.IntegerField()),
                ('version', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=20)),
                ('is_new', models.BooleanField(default=False)),
                ('fuel_type', models.CharField(max_length=20)),
                ('exchange', models.CharField(max_length=20)),
                ('distance_round', models.CharField(max_length=30)),
                ('motor', models.CharField(max_length=30)),
                ('observation', models.CharField(blank=True, max_length=250, null=True)),
                ('price_sale', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.specification')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='', null=True, upload_to=products.models.foto)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
